### ISSUE TITLE
Next 7

### ISSUE THREAD

**Issue by tomitrescak** [forthedamn/next-typed-css#1]
Hello, great plugin. Any plan to upgrade this to Next 7 ?

**Comment by zicjin** [comment]
```
(node:15612) UnhandledPromiseRejectionWarning: Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (node_modules\webpack\lib\Chunk.js:827:9)
    at node_modules\extract-text-webpack-plugin\dist\index.js:176:48
    at Array.forEach (<anonymous>)
    at node_modules\extract-text-webpack-plugin\dist\index.js:171:18
```

**Comment by forthedamn** [comment]
next-typed-css@latest support next.js 7 & 8.

> Sorry, the reply is too late.

**Comment by forthedamn** [comment]
> ```
> (node:15612) UnhandledPromiseRejectionWarning: Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
>     at Chunk.get (node_modules\webpack\lib\Chunk.js:827:9)
>     at node_modules\extract-text-webpack-plugin\dist\index.js:176:48
>     at Array.forEach (<anonymous>)
>     at node_modules\extract-text-webpack-plugin\dist\index.js:171:18
> ```

Because next use webpack4, and extract-text-webpack-plugin should chang  to mini-css-extract-plugin
