### ISSUE TITLE
scss/sass enabling setting

### ISSUE THREAD

**Issue by jerrygreen** [forthedamn/next-typed-css#2]
There are some ways in the original library to support scss/sass:

https://github.com/Jimdo/typings-for-css-modules-loader

**Comment by jerrygreen** [comment]
Oh, I mean this - https://www.npmjs.com/package/@zeit/next-sass

But looks like with https://github.com/Jimdo/typings-for-css-modules-loader it's also possible to get it working all together

**Comment by nandorojo** [comment]
+1 is there a way to get this to work the way `@zeit/next-sass` does?

**Comment by forthedamn** [comment]
OK.Now supported
```
npm install next-typed-css@latest
```

```
const withSass = require('next-typed-css/sass')
module.exports = withSass({
  // no need to set 'cssModule: true' again
  tsCssModules: true
  cssLoaderOptions: {
    // typings-for-css-modules-loader config here
    namedExport: true
  }
})
```

**Comment by jerrygreen** [comment]
@forthedamn huh, that's cool! Will check this out in a few days. If it works, it's super cool. Btw, you can probably add it to repo description then (maybe some tag too, like `sass`?):

<img width="577" alt="image" src="https://user-images.githubusercontent.com/13215662/67729570-66f27880-fa13-11e9-8554-714810b2ff67.png">

**Comment by forthedamn** [comment]
> @forthedamn huh, that's cool! Will check this out in a few days. If it works, it's super cool. Btw, you can probably add it to repo description then (maybe some tag too, like `sass`?):
> 
> <img alt="image" width="577" src="https://user-images.githubusercontent.com/13215662/67729570-66f27880-fa13-11e9-8554-714810b2ff67.png">

@JerryGreen Thanks for your suggestion.
Contact me if you have any problems.

**Comment by jerrygreen** [comment]
Just checked this - it works!

<img width="812" alt="image" src="https://user-images.githubusercontent.com/13215662/67907533-02adf100-fb9a-11e9-8e15-cbb989696a8c.png">

Figured out that's not an ideal UX though. When I have some TS errors, it's a little bit buggy, and doesn't rebuild style typings. Not to mention you have to have your server up to get it working (which is a requirement in such a concept with webpack, obviously... but not very convenient). Also if you don't open pages of you app for a while, the server may sort of "freeze", and stop webpack from rebuilding (i.e. style typings too).
